---
-
  name: Update Meerkat Chain binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop mchain service
    - name: Stop polygon edge service
      systemd:
        state: stopped
        name: mchain

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/meerkat-chain/mchain/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Meerkat Chain release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/mchain.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Meerkat Chain release
      file:
        path: /tmp/mchain
        state: directory

    ## unpack release tar
    - name: Unpack Meerkat Chain release
      unarchive:
        remote_src: yes
        src: /tmp/mchain.tar.gz
        dest: /tmp/mchain

    ## set mchain to PATH
    - name: Place Meerkat Chain binary to PATH
      copy:
        remote_src: yes
        src: /tmp/mchain/mchain
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Meerkat Chain release dir
      file:
        state: absent
        path: /tmp/mchain

    ## start polygon edge service
    - name: Start mchain service
      systemd:
        state: restarted
        name: mchain
        daemon_reload: yes
        enabled: yes