---
name: Build
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  go_build:
    name: Meerkat Chain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18.x

      - name: Build Meerkat Chain
        run: go build -tags netgo -ldflags="-s -w -linkmode external -extldflags "-static" -X \"github.com/meerkat-chain/mchain/versioning.Version=${GITHUB_REF_NAME}\" -X \"github.com/meerkat-chain/mchain/versioning.Commit=${GITHUB_SHA}\"" && tar -czvf mchain.tar.gz mchain
        env:
          CC: gcc
          CXX: g++
          GOARC: amd64
          GOOS: linux

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: mchain
          path: mchain.tar.gz
          retention-days: 3
